"""
Mock data cho test dashboard - khong can AWS/S3/GitHub.
Gia lap ket qua KICS + Trivy nhu pipeline that tra ve.
"""
import json
import os
import datetime

MOCK_DATA = {
    "customer_id": "cust-demo",
    "scanned_at": datetime.datetime.utcnow().isoformat() + "Z",
    "summary": {
        "total": 8,
        "critical": 2,
        "high": 3,
        "medium": 2,
        "low": 1,
        "info": 0,
    },
    "cloud_breakdown": [
        {"provider": "AWS", "count": 8},
    ],
    "top_categories": [
        {"category": "IAM", "count": 3},
        {"category": "Network", "count": 2},
        {"category": "Secret", "count": 2},
        {"category": "Encryption", "count": 1},
    ],
    "findings": [
        {
            "id": "kics-001",
            "query_name": "S3 Bucket Public Read Access",
            "severity": "CRITICAL",
            "cloud_provider": "AWS",
            "file": "s3.tf",
            "line": 12,
            "category": "Network",
            "platform": "aws",
            "cwe": "200",
            "description": "S3 bucket cho phep public read access. Bat ky ai cung co the doc du lieu.",
            "expected_value": "block_public_acls = true",
            "actual_value": "block_public_acls = false",
            "resource_type": "aws_s3_bucket",
            "resource_name": "bad_bucket",
            "risk_score": "9.5",
            "source": "kics",
        },
        {
            "id": "kics-002",
            "query_name": "IAM Policy Wildcard Action",
            "severity": "CRITICAL",
            "cloud_provider": "AWS",
            "file": "iam.tf",
            "line": 8,
            "category": "IAM",
            "platform": "aws",
            "cwe": "732",
            "description": "IAM policy cap quyen Action=* Resource=* - qua rong, vi phạm bat nhat (least privilege).",
            "expected_value": "Action = [specific actions]",
            "actual_value": "Action = *",
            "resource_type": "aws_iam_policy",
            "resource_name": "bad_policy",
            "risk_score": "9.0",
            "source": "kics",
        },
        {
            "id": "kics-003",
            "query_name": "Security Group Open To Internet",
            "severity": "HIGH",
            "cloud_provider": "AWS",
            "file": "sg.tf",
            "line": 15,
            "category": "Network",
            "platform": "aws",
            "cwe": "284",
            "description": "Security group cho phep ingress 0.0.0.0/0 tat ca ports.",
            "expected_value": "cidr_blocks = [10.0.0.0/8]",
            "actual_value": "cidr_blocks = [0.0.0.0/0]",
            "resource_type": "aws_security_group",
            "resource_name": "bad_sg",
            "risk_score": "8.0",
            "source": "kics",
        },
        {
            "id": "kics-004",
            "query_name": "EC2 Instance Without Encrypted Volume",
            "severity": "HIGH",
            "cloud_provider": "AWS",
            "file": "ec2.tf",
            "line": 20,
            "category": "Encryption",
            "platform": "aws",
            "cwe": "311",
            "description": "EBS root volume khong duoc ma hoa.",
            "expected_value": "encrypted = true",
            "actual_value": "encrypted = false",
            "resource_type": "aws_instance",
            "resource_name": "bad_ec2",
            "risk_score": "7.5",
            "source": "kics",
        },
        {
            "id": "trivy-001",
            "query_name": "Secret: AWS Access Key",
            "severity": "HIGH",
            "cloud_provider": "AWS",
            "file": "provider.tf",
            "line": 5,
            "category": "Secret",
            "platform": "trivy",
            "cwe": "",
            "description": "AKIA... AWS Access Key ID bi hardcode trong file Terraform.",
            "expected_value": "",
            "actual_value": "hardcoded secret detected",
            "resource_type": "",
            "resource_name": "",
            "risk_score": "7.0",
            "source": "trivy",
        },
        {
            "id": "kics-005",
            "query_name": "IAM Role Without MFA",
            "severity": "HIGH",
            "cloud_provider": "AWS",
            "file": "iam.tf",
            "line": 35,
            "category": "IAM",
            "platform": "aws",
            "cwe": "308",
            "description": "IAM role cho phep assume khong yeu cau MFA.",
            "expected_value": "condition MFA required",
            "actual_value": "no MFA condition",
            "resource_type": "aws_iam_role",
            "resource_name": "admin_role",
            "risk_score": "6.5",
            "source": "kics",
        },
        {
            "id": "kics-006",
            "query_name": "S3 Bucket Versioning Disabled",
            "severity": "MEDIUM",
            "cloud_provider": "AWS",
            "file": "s3.tf",
            "line": 25,
            "category": "IAM",
            "platform": "aws",
            "cwe": "",
            "description": "S3 bucket khong bat versioning - khong the khoi phuc sau xoa.",
            "expected_value": "versioning { enabled = true }",
            "actual_value": "versioning not configured",
            "resource_type": "aws_s3_bucket",
            "resource_name": "bad_bucket",
            "risk_score": "5.0",
            "source": "kics",
        },
        {
            "id": "trivy-002",
            "query_name": "Secret: Slack Webhook URL",
            "severity": "MEDIUM",
            "cloud_provider": "AWS",
            "file": "notifications.tf",
            "line": 3,
            "category": "Secret",
            "platform": "trivy",
            "cwe": "",
            "description": "Slack webhook URL bi hardcode.",
            "expected_value": "",
            "actual_value": "hardcoded secret detected",
            "resource_type": "",
            "resource_name": "",
            "risk_score": "4.5",
            "source": "trivy",
        },
        {
            "id": "kics-007",
            "query_name": "CloudTrail Logging Disabled",
            "severity": "LOW",
            "cloud_provider": "AWS",
            "file": "logging.tf",
            "line": 1,
            "category": "IAM",
            "platform": "aws",
            "cwe": "",
            "description": "Khong phat hien CloudTrail logging - khong co audit trail.",
            "expected_value": "CloudTrail enabled",
            "actual_value": "CloudTrail not found",
            "resource_type": "",
            "resource_name": "",
            "risk_score": "3.0",
            "source": "kics",
        },
    ],
}


def get_mock_data():
    return MOCK_DATA
