import React, { useCallback, useEffect, useState } from 'react';
import { fetchAlerts } from '../utils/api';

const C = { CRITICAL: '#f85149', HIGH: '#f0883e', MEDIUM: '#d29922', LOW: '#3fb950', INFO: '#58a6ff' };
const fmt = v => v ? new Date(v).toLocaleString('vi-VN') : 'N/A';

export default function AlertsPage() {
  const [data, setData] = useState(null), [page, setPage] = useState(1), [filter, setFilter] = useState('ALL'), [q, setQ] = useState(''), [detail, setDetail] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const load = useCallback(async (p = 1) => { setLoading(true); setError(''); try { setData(await fetchAlerts(p, 25, q)); setPage(p); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [q]);
  useEffect(() => { load(); }, [load]);
  const alerts = (data?.alerts || []).filter(a => (filter === 'ALL' || a.severity === filter) && (!q || JSON.stringify(a).toLowerCase().includes(q.toLowerCase())));
  return <main style={s.page}>
    <header style={s.header}><div><h1 style={s.h1}>Cảnh báo bảo mật</h1><p style={s.muted}>Detection alerts · {data?.total || 0} bản ghi từ Elasticsearch</p></div><button style={s.refresh} onClick={() => load(page)}>{loading ? 'Đang tải...' : 'Làm mới'}</button></header>
    {error && <div style={s.error}>Không thể tải alert: {error}</div>}
    <div style={s.filters}>{['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'].map(x => <button key={x} onClick={() => setFilter(x)} style={{ ...s.filter, ...(filter === x ? { background: C[x] || '#1f6feb', color: '#fff' } : {}) }}>{x === 'ALL' ? 'Tất cả' : x}</button>)}<input style={s.search} value={q} onChange={e => setQ(e.target.value)} placeholder="Tìm rule, mô tả, host, user..." /></div>
    <section style={s.list}>{loading && <div style={s.empty}>Đang tải dữ liệu cảnh báo...</div>}{!loading && !alerts.length && <div style={s.empty}>Không có cảnh báo phù hợp.</div>}{alerts.map((a, i) => { const color = C[a.severity] || '#8b949e'; return <button key={a.id || i} style={{ ...s.card, borderLeftColor: color }} onClick={() => setDetail(a)}><div style={s.cardTop}><span style={{ ...s.sev, color, borderColor: color }}>{a.severity || 'Không có severity'}</span><strong style={s.rule}>{a.title || 'Không có tên rule trong dữ liệu'}</strong></div><div style={s.meta}>{fmt(a.timestamp)} · {a.category || 'Không có category'}{a.host ? ` · Host: ${a.host}` : ''}{a.user ? ` · User: ${a.user}` : ''}</div><p style={s.reason}>{a.description || 'Không có description/reason trong JSON alert.'}</p><div style={s.tags}>{a.rule_id ? `Rule ID: ${a.rule_id}` : 'Không có Rule ID'}{a.risk_score !== undefined && a.risk_score !== null ? ` · Risk score: ${a.risk_score}` : ''}{a.rule_type ? ` · Type: ${a.rule_type}` : ''}<span>› Xem JSON</span></div></button>; })}</section>
    {!loading && (data?.total_pages || 0) > 1 && <nav style={s.pagination}><button disabled={page === 1} onClick={() => load(page - 1)}>← Trước</button><b>Trang {page} / {data.total_pages}</b><button disabled={page === data.total_pages} onClick={() => load(page + 1)}>Sau →</button></nav>}
    {detail && <div style={s.overlay} onClick={() => setDetail(null)}><aside style={s.drawer} onClick={e => e.stopPropagation()}><button style={s.close} onClick={() => setDetail(null)}>×</button><h2>{detail.title || 'Alert detail'}</h2><p style={s.muted}>{detail.severity} · {fmt(detail.timestamp)}{detail.host ? ` · ${detail.host}` : ''}</p><h3>Mô tả / Reason</h3><p>{detail.description || 'Không có description trong JSON.'}</p><h3>Thông tin rule</h3><p>Rule ID: {detail.rule_id || 'N/A'} · Risk score: {detail.risk_score ?? 'N/A'} · Type: {detail.rule_type || 'N/A'}</p><h3>Raw Elasticsearch alert</h3><pre style={s.raw}>{JSON.stringify(detail.raw || detail, null, 2)}</pre></aside></div>}
  </main>;
}

const s = { page: { color: '#e6edf3' }, header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22 }, h1: { margin: 0, fontSize: 24 }, muted: { color: '#8b949e', fontSize: 12 }, refresh: { background: '#238636', color: '#fff', border: 0, borderRadius: 6, padding: '9px 16px' }, error: { background: '#3d1515', color: '#ffa198', padding: 12, borderRadius: 6 }, filters: { display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 16 }, filter: { background: '#161b22', color: '#8b949e', border: '1px solid #30363d', borderRadius: 6, padding: '7px 12px' }, search: { flex: 1, minWidth: 240, background: '#0d1117', color: '#e6edf3', border: '1px solid #30363d', borderRadius: 6, padding: '8px 12px' }, list: { display: 'flex', flexDirection: 'column', gap: 10 }, card: { textAlign: 'left', background: '#161b22', color: '#e6edf3', border: '1px solid #30363d', borderLeft: '4px solid', borderRadius: 8, padding: 16 }, cardTop: { display: 'flex', gap: 12, alignItems: 'center' }, sev: { border: '1px solid', borderRadius: 4, padding: '3px 6px', fontSize: 10, fontWeight: 700 }, rule: { fontSize: 15, flex: 1 }, meta: { color: '#8b949e', fontSize: 11, marginTop: 8 }, reason: { color: '#c9d1d9', lineHeight: 1.5, margin: '12px 0' }, tags: { color: '#58a6ff', fontSize: 11, display: 'flex', justifyContent: 'space-between', gap: 10 }, empty: { textAlign: 'center', padding: 60, color: '#8b949e' }, pagination: { display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 18, padding: 22 }, overlay: { position: 'fixed', inset: 0, background: '#0009', zIndex: 20 }, drawer: { position: 'absolute', right: 0, top: 0, height: '100%', width: 'min(700px, 92vw)', background: '#161b22', padding: 26, overflow: 'auto' }, close: { float: 'right', background: 'none', border: 0, color: '#8b949e', fontSize: 28 }, raw: { background: '#0d1117', padding: 14, color: '#c9d1d9', fontSize: 11, whiteSpace: 'pre-wrap', wordBreak: 'break-word' } };
