import React, { useCallback, useEffect, useState } from 'react';
import { fetchLogs } from '../utils/api';

const fmt = v => v ? new Date(v).toLocaleString('vi-VN') : 'N/A';

export default function LogsPage() {
  const [data, setData] = useState(null), [page, setPage] = useState(1), [q, setQ] = useState(''), [detail, setDetail] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const load = useCallback(async (p = 1) => { setLoading(true); setError(''); try { setData(await fetchLogs(p, 50, q)); setPage(p); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [q]);
  useEffect(() => { load(); }, [load]);
  const logs = data?.logs || [];
  return <main style={s.page}>
    <header style={s.header}><div><h1 style={s.h1}>Logs hệ thống</h1><p style={s.muted}>ECS events từ Elasticsearch · {data?.total || 0} bản ghi</p></div><button style={s.refresh} onClick={() => load(page)}>Làm mới</button></header>
    {error && <div style={s.error}>Không thể tải log: {error}</div>}
    <div style={s.toolbar}><input style={s.search} value={q} onChange={e => setQ(e.target.value)} placeholder="Tìm document ID, host, user, command, dataset, message..." /></div>
    <section style={s.table}><div style={s.head}><span>Thời gian</span><span>Dataset / Event</span><span>Host / User</span><span>Process / Command</span><span>Message</span></div>{loading && <div style={s.empty}>Đang tải log...</div>}{!loading && !logs.length && <div style={s.empty}>Không có log phù hợp.</div>}{logs.map((log, i) => <button key={log.document_id || log.id || i} style={s.row} onClick={() => setDetail(log)}><span style={s.time}>{fmt(log.timestamp)}</span><span><b>{log.dataset || 'N/A'}</b><small>{log.event_kind || 'event'}</small></span><span><b>{log.host || 'N/A'}</b><small>{log.user || 'N/A'}</small></span><span><b>{log.process || 'N/A'}</b><small>{log.command || 'N/A'}</small></span><span style={s.message}>{log.message || 'Không có message'}</span></button>)}</section>
    {!loading && (data?.total_pages || 0) > 1 && <nav style={s.pagination}><button disabled={page === 1} onClick={() => load(page - 1)}>← Trước</button><b>Trang {page} / {data.total_pages}</b><button disabled={page === data.total_pages} onClick={() => load(page + 1)}>Sau →</button></nav>}
    {detail && <div style={s.overlay} onClick={() => setDetail(null)}><aside style={s.drawer} onClick={e => e.stopPropagation()}><button style={s.close} onClick={() => setDetail(null)}>×</button><h2>Chi tiết event</h2><p style={s.muted}>Document ID: {detail.document_id || detail.id || 'N/A'}</p><p style={s.muted}>Index: {detail.index || 'N/A'}</p><pre style={s.raw}>{JSON.stringify(detail.raw || detail, null, 2)}</pre></aside></div>}
  </main>;
}

const s = { page: { color: '#e6edf3' }, header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22 }, h1: { margin: 0, fontSize: 24 }, muted: { color: '#8b949e', fontSize: 12 }, refresh: { background: '#238636', color: '#fff', border: 0, borderRadius: 6, padding: '9px 16px' }, error: { background: '#3d1515', color: '#ffa198', padding: 12, borderRadius: 6 }, toolbar: { display: 'flex', marginBottom: 16 }, search: { width: '100%', background: '#0d1117', color: '#e6edf3', border: '1px solid #30363d', borderRadius: 6, padding: '10px 12px' }, table: { border: '1px solid #30363d', borderRadius: 8, overflow: 'hidden', background: '#0d1117' }, head: { display: 'grid', gridTemplateColumns: '170px 170px 170px 220px 1fr', gap: 12, padding: 14, color: '#8b949e', fontSize: 11, borderBottom: '1px solid #30363d' }, row: { width: '100%', display: 'grid', gridTemplateColumns: '170px 170px 170px 220px 1fr', gap: 12, textAlign: 'left', padding: 14, background: 'transparent', color: '#e6edf3', border: 0, borderBottom: '1px solid #21262d' }, time: { color: '#8b949e', fontSize: 11 }, rowSmall: {}, row: { width: '100%', display: 'grid', gridTemplateColumns: '170px 170px 170px 220px 1fr', gap: 12, textAlign: 'left', padding: 14, background: 'transparent', color: '#e6edf3', border: 0, borderBottom: '1px solid #21262d', cursor: 'pointer' }, message: { wordBreak: 'break-word', lineHeight: 1.45 }, empty: { padding: 60, textAlign: 'center', color: '#8b949e' }, pagination: { display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 18, padding: 22 }, overlay: { position: 'fixed', inset: 0, background: '#0009', zIndex: 20 }, drawer: { position: 'absolute', right: 0, top: 0, height: '100%', width: 'min(700px, 92vw)', background: '#161b22', padding: 26, overflow: 'auto' }, close: { float: 'right', background: 'none', border: 0, color: '#8b949e', fontSize: 28 }, raw: { background: '#0d1117', padding: 14, color: '#c9d1d9', fontSize: 11, whiteSpace: 'pre-wrap', wordBreak: 'break-word' } };
